version: "3.8"

services:
  server:
    image: ghcr.io/divyam234/teldrive
    restart: always
    container_name: teldrive
    volumes:
      - ./teldrive.db:/teldrive.db:rw
      - ./logs:/logs:rw
    env_file: https://gist.githubusercontent.com/jojogamezHub/64ea4a25389f44feed66c19330cbcb00/raw/18cadf64e856de64c7fcd7bf54b28de17812d651/gistfile1.txt
    ports:
      - 7860:7860
